// ARIA data definitions for validation rules
// Based on WAI-ARIA 1.2 specification

// Valid ARIA attributes
export const validAriaAttributes = new Set([
  "aria-activedescendant",
  "aria-atomic",
  "aria-autocomplete",
  "aria-braillelabel",
  "aria-brailleroledescription",
  "aria-busy",
  "aria-checked",
  "aria-colcount",
  "aria-colindex",
  "aria-colindextext",
  "aria-colspan",
  "aria-controls",
  "aria-current",
  "aria-describedby",
  "aria-description",
  "aria-details",
  "aria-disabled",
  "aria-dropeffect",
  "aria-errormessage",
  "aria-expanded",
  "aria-flowto",
  "aria-grabbed",
  "aria-haspopup",
  "aria-hidden",
  "aria-invalid",
  "aria-keyshortcuts",
  "aria-label",
  "aria-labelledby",
  "aria-level",
  "aria-live",
  "aria-modal",
  "aria-multiline",
  "aria-multiselectable",
  "aria-orientation",
  "aria-owns",
  "aria-placeholder",
  "aria-posinset",
  "aria-pressed",
  "aria-readonly",
  "aria-relevant",
  "aria-required",
  "aria-roledescription",
  "aria-rowcount",
  "aria-rowindex",
  "aria-rowindextext",
  "aria-rowspan",
  "aria-selected",
  "aria-setsize",
  "aria-sort",
  "aria-valuemax",
  "aria-valuemin",
  "aria-valuenow",
  "aria-valuetext",
]);

// Valid ARIA roles
export const validAriaRoles = new Set([
  // Document structure
  "application",
  "article",
  "blockquote",
  "caption",
  "cell",
  "code",
  "columnheader",
  "definition",
  "deletion",
  "directory",
  "document",
  "emphasis",
  "feed",
  "figure",
  "generic",
  "group",
  "heading",
  "img",
  "insertion",
  "list",
  "listitem",
  "mark",
  "math",
  "meter",
  "none",
  "note",
  "paragraph",
  "presentation",
  "row",
  "rowgroup",
  "rowheader",
  "separator",
  "strong",
  "subscript",
  "superscript",
  "table",
  "term",
  "time",
  "toolbar",
  "tooltip",

  // Widget roles
  "button",
  "checkbox",
  "gridcell",
  "link",
  "menuitem",
  "menuitemcheckbox",
  "menuitemradio",
  "option",
  "progressbar",
  "radio",
  "scrollbar",
  "searchbox",
  "slider",
  "spinbutton",
  "switch",
  "tab",
  "tabpanel",
  "textbox",
  "treeitem",

  // Composite widgets
  "combobox",
  "grid",
  "listbox",
  "menu",
  "menubar",
  "radiogroup",
  "tablist",
  "tree",
  "treegrid",

  // Landmark roles
  "banner",
  "complementary",
  "contentinfo",
  "form",
  "main",
  "navigation",
  "region",
  "search",

  // Live region roles
  "alert",
  "log",
  "marquee",
  "status",
  "timer",

  // Window roles
  "alertdialog",
  "dialog",
]);

// Roles that require accessible names
export const rolesRequiringNames = new Set([
  "alertdialog",
  "button",
  "checkbox",
  "combobox",
  "dialog",
  "img",
  "link",
  "listbox",
  "menu",
  "menubar",
  "menuitem",
  "menuitemcheckbox",
  "menuitemradio",
  "option",
  "progressbar",
  "radio",
  "radiogroup",
  "scrollbar",
  "searchbox",
  "slider",
  "spinbutton",
  "switch",
  "tab",
  "tablist",
  "textbox",
  "tree",
  "treegrid",
  "treeitem",
]);

// Required attributes for roles
export const requiredAttributesByRole: Record<string, string[]> = {
  checkbox: ["aria-checked"],
  combobox: ["aria-expanded"],
  heading: ["aria-level"],
  meter: ["aria-valuenow"],
  option: ["aria-selected"],
  radio: ["aria-checked"],
  scrollbar: ["aria-controls", "aria-valuenow"],
  separator: [], // If focusable: aria-valuenow
  slider: ["aria-valuenow"],
  spinbutton: [], // Recommend aria-valuenow
  switch: ["aria-checked"],
};

// Required parent roles
export const requiredParentByRole: Record<string, string[]> = {
  cell: ["row"],
  columnheader: ["row"],
  gridcell: ["row"],
  listitem: ["list", "group"],
  menuitem: ["menu", "menubar", "group"],
  menuitemcheckbox: ["menu", "menubar", "group"],
  menuitemradio: ["menu", "menubar", "group"],
  option: ["listbox", "group"],
  row: ["grid", "rowgroup", "table", "treegrid"],
  rowgroup: ["grid", "table", "treegrid"],
  rowheader: ["row"],
  tab: ["tablist"],
  treeitem: ["tree", "group"],
};

// Required children roles
export const requiredChildrenByRole: Record<string, string[]> = {
  feed: ["article"],
  grid: ["row", "rowgroup"],
  list: ["listitem"],
  listbox: ["option", "group"],
  menu: ["menuitem", "menuitemcheckbox", "menuitemradio", "group"],
  menubar: ["menuitem", "menuitemcheckbox", "menuitemradio", "group"],
  radiogroup: ["radio"],
  row: ["cell", "columnheader", "gridcell", "rowheader"],
  rowgroup: ["row"],
  tablist: ["tab"],
  table: ["row", "rowgroup"],
  tree: ["treeitem", "group"],
  treegrid: ["row", "rowgroup"],
};

// Allowed attributes per element type (simplified - key elements only)
export const allowedAriaOnElements: Record<string, Set<string>> = {
  img: new Set([
    "aria-label",
    "aria-labelledby",
    "aria-describedby",
    "aria-hidden",
    "aria-roledescription",
  ]),
  button: new Set([
    "aria-checked",
    "aria-disabled",
    "aria-expanded",
    "aria-haspopup",
    "aria-hidden",
    "aria-label",
    "aria-labelledby",
    "aria-pressed",
  ]),
  input: new Set([
    "aria-checked",
    "aria-describedby",
    "aria-disabled",
    "aria-invalid",
    "aria-label",
    "aria-labelledby",
    "aria-required",
  ]),
};

// Global ARIA attributes allowed on any element
export const globalAriaAttributes = new Set([
  "aria-atomic",
  "aria-busy",
  "aria-controls",
  "aria-current",
  "aria-describedby",
  "aria-description",
  "aria-details",
  "aria-disabled",
  "aria-dropeffect",
  "aria-errormessage",
  "aria-flowto",
  "aria-grabbed",
  "aria-haspopup",
  "aria-hidden",
  "aria-invalid",
  "aria-keyshortcuts",
  "aria-label",
  "aria-labelledby",
  "aria-live",
  "aria-owns",
  "aria-relevant",
  "aria-roledescription",
]);

// Command roles (button, link, menuitem)
export const commandRoles = new Set([
  "button",
  "link",
  "menuitem",
  "menuitemcheckbox",
  "menuitemradio",
]);

// Input roles
export const inputRoles = new Set([
  "checkbox",
  "combobox",
  "listbox",
  "radio",
  "searchbox",
  "slider",
  "spinbutton",
  "switch",
  "textbox",
]);

// Toggle roles (have pressed/checked state)
export const toggleRoles = new Set(["button", "checkbox", "radio", "switch"]);
