#!/usr/bin/env bun

import { existsSync, readFileSync, readdirSync, realpathSync } from "node:fs";
import { dirname, join, parse, resolve } from "node:path";

interface PackageJson {
  name?: string;
  version?: string;
  license?: string;
  repository?: string | { url?: string };
  dependencies?: Record<string, string>;
  optionalDependencies?: Record<string, string>;
  peerDependencies?: Record<string, string>;
}

interface PackageNotice {
  name: string;
  version: string;
  license: string;
  source: string;
  noticeHashes: string[];
}

const root = resolve(import.meta.dir, "..");
const workspacePackages = new Map<string, string>();

for (const directory of [join(root, "apps", "cli"), ...new Bun.Glob("packages/*").scanSync(root)]) {
  const absolute = resolve(root, directory);
  const packagePath = join(absolute, "package.json");
  if (!existsSync(packagePath)) continue;
  const pkg = JSON.parse(readFileSync(packagePath, "utf8")) as PackageJson;
  if (pkg.name) workspacePackages.set(pkg.name, absolute);
}

function dependencyPackageDirectory(name: string, fromDirectory: string): string | null {
  const workspace = workspacePackages.get(name);
  if (workspace) return workspace;

  let cursor = fromDirectory;
  while (true) {
    const candidate = join(cursor, "node_modules", ...name.split("/"), "package.json");
    if (existsSync(candidate)) return dirname(realpathSync(candidate));
    const parent = dirname(cursor);
    if (parent === cursor) return null;
    cursor = parent;
  }
}

function repositoryUrl(repository: PackageJson["repository"]): string {
  const value = typeof repository === "string" ? repository : repository?.url;
  if (!value) return "";
  const normalized = value
    .replace(/^git\+/, "")
    .replace(/^git@github\.com:/, "https://github.com/")
    .replace(/^ssh:\/\/git@github\.com[:/]/, "https://github.com/")
    .replace(/^git:\/\/git@github\.com\//, "https://github.com/")
    .replace(/^git:\/\/github\.com\//, "https://github.com/")
    .replace(/\.git$/, "");
  return /^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(normalized)
    ? `https://github.com/${normalized}`
    : normalized;
}

function hashText(value: string): string {
  return new Bun.CryptoHasher("sha256").update(value).digest("hex");
}

const packages = new Map<string, PackageNotice>();
const noticeTexts = new Map<string, { filename: string; text: string; packages: Set<string> }>();
const visitedDirectories = new Set<string>();

function visit(directory: string): void {
  const realDirectory = realpathSync(directory);
  if (visitedDirectories.has(realDirectory)) return;
  visitedDirectories.add(realDirectory);

  const pkg = JSON.parse(readFileSync(join(realDirectory, "package.json"), "utf8")) as PackageJson;
  const dependencyNames = new Set([
    ...Object.keys(pkg.dependencies ?? {}),
    ...Object.keys(pkg.optionalDependencies ?? {}),
    ...Object.keys(pkg.peerDependencies ?? {}),
  ]);

  if (pkg.name && !pkg.name.startsWith("@squirrelscan/")) {
    const id = `${pkg.name}@${pkg.version ?? "unknown"}`;
    const noticeHashes: string[] = [];
    for (const filename of readdirSync(realDirectory).sort()) {
      if (!/^(licen[cs]e|copying|notice)(\..*)?$/i.test(filename)) continue;
      const path = join(realDirectory, filename);
      let text: string;
      try {
        text = readFileSync(path, "utf8").trim();
      } catch {
        continue;
      }
      if (!text) continue;
      const hash = hashText(text);
      noticeHashes.push(hash);
      const existing = noticeTexts.get(hash);
      if (existing) {
        existing.packages.add(id);
      } else {
        noticeTexts.set(hash, { filename, text, packages: new Set([id]) });
      }
    }

    packages.set(id, {
      name: pkg.name,
      version: pkg.version ?? "unknown",
      license: pkg.license ?? "SEE PACKAGE",
      source: repositoryUrl(pkg.repository),
      noticeHashes,
    });
  }

  for (const name of [...dependencyNames].sort()) {
    const dependencyDirectory = dependencyPackageDirectory(name, realDirectory);
    if (dependencyDirectory) visit(dependencyDirectory);
  }
}

visit(join(root, "apps", "cli"));

const lines = [
  "# Third-Party Notices",
  "",
  "The squirrelscan CLI distribution includes the following third-party software.",
  "This file is generated by `scripts/generate-third-party-notices.ts` from the",
  "runtime dependency closure of `apps/cli`.",
  "",
  "## Package Inventory",
  "",
  "| Package | License | Source |",
  "| --- | --- | --- |",
];

for (const notice of [...packages.values()].sort((a, b) =>
  `${a.name}@${a.version}`.localeCompare(`${b.name}@${b.version}`),
)) {
  const source = notice.source ? `[source](${notice.source})` : "-";
  lines.push(`| \`${notice.name}@${notice.version}\` | ${notice.license} | ${source} |`);
}

lines.push("", "## License And Notice Texts", "");

for (const [hash, notice] of [...noticeTexts].sort(([a], [b]) => a.localeCompare(b))) {
  lines.push(
    `### ${notice.filename} (${hash.slice(0, 12)})`,
    "",
    `Packages: ${[...notice.packages]
      .sort()
      .map((id) => `\`${id}\``)
      .join(", ")}`,
    "",
    ...notice.text
      .split(/\r?\n/)
      .map((line) => line.replace(/[ \t]+$/, ""))
      .map((line) => (line ? `    ${line}` : "")),
    "",
  );
}

const output = `${lines.join("\n").replace(/\n+$/, "")}\n`;
await Bun.write(join(root, "THIRD_PARTY_NOTICES.md"), output);
await Bun.write(join(root, "npm", "THIRD_PARTY_NOTICES.md"), output);
console.log(`Wrote notices for ${packages.size} packages (${noticeTexts.size} unique texts).`);
