// White-label report branding (#810): Team orgs render reports without
// squirrelscan branding, using their own logo (or name) in the header. These
// pin the on/off behaviour for every renderer; the "off" path must stay
// byte-identical to the default branded output.

import { describe, expect, test } from "bun:test";

import type { ReportBranding } from "@squirrelscan/core-contracts";
import type { AuditReport } from "../src/types";
import { renderHtml } from "../src/output/html";
import { renderMarkdown } from "../src/output/markdown";
import { renderText } from "../src/output/text";
import { renderXml } from "../src/output/xml";

function baseReport(overrides: Partial<AuditReport> = {}): AuditReport {
  return {
    baseUrl: "https://acme.example",
    timestamp: "2026-06-16T14:30:00.000Z",
    totalPages: 1,
    passed: 0,
    warnings: 0,
    failed: 0,
    ruleResults: {},
    generatorVersion: "1.2.3",
    lockedRules: [{ id: "a", name: "Locked Check" }],
    ...overrides,
  };
}

const WHITE_LABEL: ReportBranding = {
  whiteLabel: true,
  orgLogoUrl: "https://api.squirrelscan.com/v1/organizations/org_1/logo?v=1",
  orgName: "Acme Inc",
};

describe("white-label html", () => {
  test("default (no branding) keeps squirrelscan logo, footer, and og:site_name", () => {
    const html = renderHtml(baseReport(), { reportId: "r1" });
    expect(html).toContain("squirrelscan");
    expect(html).toContain('href="https://squirrelscan.com"');
    expect(html).toContain("Generated by");
    expect(html).toContain('content="squirrelscan"');
  });

  test("white-label hides squirrelscan wordmark, footer credit, and CTA", () => {
    const html = renderHtml(baseReport(), { reportId: "r1", branding: WHITE_LABEL });
    // No squirrelscan wordmark link or "Generated by" credit.
    expect(html).not.toContain('href="https://squirrelscan.com"');
    expect(html).not.toContain("Generated by");
    // The locked-rules upsell / account CTA is dropped entirely.
    expect(html).not.toContain('class="locked-section"');
    // og:site_name uses the org name, not squirrelscan.
    expect(html).toContain('property="og:site_name" content="Acme Inc"');
    expect(html).not.toContain('content="squirrelscan"');
  });

  test("white-label shows the org logo when set", () => {
    const html = renderHtml(baseReport(), { branding: WHITE_LABEL });
    expect(html).toContain(WHITE_LABEL.orgLogoUrl as string);
    expect(html).toContain('class="wl-logo"');
  });

  test("white-label falls back to the org name as plain text when no logo", () => {
    const html = renderHtml(baseReport(), {
      branding: { whiteLabel: true, orgName: "Acme Inc" },
    });
    expect(html).toContain('class="wl-wordmark"');
    expect(html).toContain("Acme Inc");
    expect(html).not.toContain('class="wl-logo"');
  });
});

describe("white-label markdown", () => {
  test("default keeps the squirrelscan header and generated-by footer", () => {
    const md = renderMarkdown(baseReport(), { version: "1.2.3" });
    expect(md).toContain("# squirrelscan Audit Report");
    expect(md).toContain("Generated by [squirrelscan]");
  });

  test("white-label drops the squirrelscan header and footer", () => {
    const md = renderMarkdown(baseReport(), { version: "1.2.3", branding: WHITE_LABEL });
    expect(md).not.toContain("squirrelscan");
    expect(md).toContain("# Acme Inc Audit Report");
    expect(md).not.toContain("Generated by");
  });
});

describe("white-label text + xml", () => {
  test("text default vs white-label", () => {
    expect(renderText(baseReport())).toContain("Generated by squirrelscan.com");
    const wl = renderText(baseReport(), { branding: WHITE_LABEL });
    expect(wl).not.toContain("squirrelscan");
    expect(wl).toContain("Acme Inc");
  });

  test("xml uses a neutral root element when white-label", () => {
    expect(renderXml(baseReport())).toContain("<squirrelscan-audit");
    const wl = renderXml(baseReport(), { branding: WHITE_LABEL });
    expect(wl).not.toContain("squirrelscan");
    expect(wl).toContain("<audit ");
    expect(wl).toContain("</audit>");
  });
});
